// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaInterface.Models;

#nullable disable

namespace SistemaInterface.Migrations
{
    [DbContext(typeof(WpfDbContext))]
    [Migration("20260430225203_AdicionarTabelaRelatorios")]
    partial class AdicionarTabelaRelatorios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("SistemaInterface.Models.ProdutoDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProdutosLocal");
                });

            modelBuilder.Entity("SistemaInterface.Models.RelatorioDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalItens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotalEstoque")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricoRelatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
